# conda build -c http://stanlan-ate.corp.continuum.io/api/repo/hive -c conda-forge --python 3.7 recipe/

package:
  name: metagraph-igraph
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  string: py{{ PY_VER }}h{{ PKG_HASH }}_{{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - metagraph

  run:
    - python
    - setuptools
    - metagraph
    - python-igraph

test:
  requires:
    - pytest
    - python-igraph
#    - pytest-cov
#    - coverage
#    - black

  commands:
    - pytest --pyargs metagraph_igraph.tests

about:
  home: https://github.com/ContinuumIO/metagraph-igraph
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Metagraph plugin for the python-igraph library'
  description: |
      Plugin for metagraph exposing the data structures and algorithms of python-igraph
  dev_url: https://github.com/ContinuumIO/metagraph-igraph